[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]

[tool]
[tool.poetry]
authors = ["draju1980 <draju@outlook.com>"]
description = ""
name = "hello-world"
version = "0.1.0"
[tool.poetry.dependencies]
ipython = "^7.14"
python = "^3.7"
[tool.poetry.dev-dependencies]
