v=int(input("Enetr the seconds "))
x=int(v%86400)
d=int((v-x)/86400)
#print("days ",d)
y=int(x%3600)
h=int((x-y)/3600)
#print("hours",h)
s=int(y%60)
m=int((y-s)/60)
#print("minutes",m)
#print("seconds",s)
print(d,"days",h,"hours",m,"minutes",s,"seconds")